# Generated by AI

import sys
from collections import defaultdict

def read_dictionary(file_path):
    """Reads the dictionary file into a dict of lists keyed by section letter."""
    sections = defaultdict(list)
    current_section = None

    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if len(line) == 1 and line.isalpha():  # Section header
                current_section = line.upper()
            elif ' - ' in line and current_section:
                sections[current_section].append(line[2:])
    return sections

def write_dictionary(file_path, sections):
    """Writes the dictionary back to the file, sorted alphabetically."""
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(`Abbreviations Dictionary\n========================\n\n `)
        for section in sorted(sections.keys()):
            f.write('~~\n')
            f.write(section + '\n')
            f.write('~~\n\n')
            for entry in sorted(sections[section], key=lambda x: x.lower()):
                f.write('| ' + entry + '\n')
            f.write('\n')

def add_entry(file_path, abbr, explanation):
    sections = read_dictionary(file_path)
    section = abbr[0].upper()
    entry = f"{abbr} - {explanation}"

    if section not in sections:
        sections[section] = []

    if entry not in sections[section]:
        sections[section].append(entry)

    write_dictionary(file_path, sections)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python add_abbr.py <dictionary_file> <abbreviation> <explanation>")
        sys.exit(1)

    dictionary_file = sys.argv[1]
    abbreviation = sys.argv[2]
    explanation = sys.argv[3]

    add_entry(dictionary_file, abbreviation, explanation)
