name: Makefile CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get install -y gcc-riscv64-unknown-elf dosfstools e2fsprogs mtools
    - name: Try building
      run: make
